// AUTO-GENERATED by scripts/gen-redirect-worker.ts — DO NOT EDIT BY HAND.
// Redirect-only Worker bound to teammovemortgage.com/*. It 301s every request
// to the matching path on russelldsmith.com, preserving the query string.
// KEEP-FOREVER INFRASTRUCTURE: the backlinks point at old URLs permanently.
//
// mapPath() mirrors lib/redirects.ts exactly; scripts/test-redirects.ts imports
// both and asserts they agree over every fixture, so this can't silently drift.

const DEST = "https://russelldsmith.com";

const EXPLICIT = {
  "/": "/",
  "/index.php": "/",
  "/404.php": "/",
  "/usda/": "/usda-loans/",
  "/usda-loans.php": "/usda-loans/",
  "/fha/": "/fha-loans/",
  "/fha-loans.php": "/fha-loans/",
  "/va-loan/": "/va-loans/",
  "/va-loans.php": "/va-loans/",
  "/construction-perm/": "/construction-perm/",
  "/rehab-loans/": "/renovation-loans/",
  "/mortgage-calculators/": "/mortgage-calculators/",
  "/down-payment-assistance-nc-sc/": "/down-payment-assistance/",
  "/down-payment-assistance.php": "/down-payment-assistance/",
  "/va-funding-fee-tables/": "/va-funding-fee-tables/",
  "/reverse-mortgages-nc-sc/": "/reverse-mortgages/",
  "/rental-properties/": "/investment-property-loans/",
  "/vacation-home-purchase/": "/blog/second-home/",
  "/1st-time-buyer-mcc-tax-credit-nc/": "/blog/mortgage-credit-certificate/",
  "/jumbo/": "/jumbo-loans/",
  "/jumbo-loans.php": "/jumbo-loans/",
  "/lot-loans.php": "/construction-perm/",
  "/contact-us/": "/contact/",
  "/contact-team-move.php": "/contact/",
  "/our-team/": "/about/",
  "/about-team-move.php": "/about/",
  "/our-process/": "/about/"
};

function ensureTrailingSlash(p) {
  if (p === "") return "/";
  if (p.endsWith("/")) return p;
  const last = p.split("/").pop() ?? "";
  if (last.includes(".")) return p;
  return p + "/";
}

export function mapPath(pathname) {
  let p = pathname || "/";
  if (!p.startsWith("/")) p = "/" + p;

  // 1. Explicit map (exact, then with/without trailing slash).
  if (EXPLICIT[p] !== undefined) return EXPLICIT[p];
  const alt = p.endsWith("/") ? p.slice(0, -1) : p + "/";
  if (EXPLICIT[alt] !== undefined) return EXPLICIT[alt];

  // 2. Gen 2: /blog/YYYY/MM/DD/{slug}/ -> /blog/{slug}/
  let m = p.replace(/^\/blog\/\d{4}\/\d{2}\/\d{2}\/(.+)$/, "/blog/$1");
  if (m !== p) return ensureTrailingSlash(m);

  // 3. Gen 1: /YYYY/MM/DD/{slug}/ -> /blog/{slug}/
  m = p.replace(/^\/\d{4}\/\d{2}\/\d{2}\/(.+)$/, "/blog/$1");
  if (m !== p) return ensureTrailingSlash(m);

  // 4. Double-blog cleanup: /blog/blog/{slug}/ -> /blog/{slug}/
  m = p.replace(/^\/blog\/blog\/(.+)$/, "/blog/$1");
  if (m !== p) return ensureTrailingSlash(m);

  // 5. Old category root: /category/{cat}/ -> /blog/category/{cat}/
  m = p.replace(/^\/category\/(.+)$/, "/blog/category/$1");
  if (m !== p) return ensureTrailingSlash(m);

  // 6. Live pass-through.
  return p;
}

export default {
  async fetch(request) {
    const url = new URL(request.url);
    return Response.redirect(DEST + mapPath(url.pathname) + url.search, 301);
  },
};
