/**
 * Generates the redirect-only Worker for teammovemortgage.com from the shared
 * redirect logic + the CSV explicit rows. Output is self-contained plain JS
 * (Cloudflare Worker module). It also `export`s mapPath so the redirect test
 * can assert the shipped Worker and lib/redirects.ts never drift.
 *
 *   tsx scripts/gen-redirect-worker.ts
 */
import fs from "node:fs";
import path from "node:path";
import { buildMergedExplicit } from "./lib/redirect-map.js";

const merged = buildMergedExplicit();
const OUT_DIR = path.join(process.cwd(), "workers", "redirect");

const worker = `// AUTO-GENERATED by scripts/gen-redirect-worker.ts — DO NOT EDIT BY HAND.
// Redirect-only Worker bound to teammovemortgage.com/*. It 301s every request
// to the matching path on russelldsmith.com, preserving the query string.
// KEEP-FOREVER INFRASTRUCTURE: the backlinks point at old URLs permanently.
//
// mapPath() mirrors lib/redirects.ts exactly; scripts/test-redirects.ts imports
// both and asserts they agree over every fixture, so this can't silently drift.

const DEST = "https://russelldsmith.com";

const EXPLICIT = ${JSON.stringify(merged, null, 2)};

function ensureTrailingSlash(p) {
  if (p === "") return "/";
  if (p.endsWith("/")) return p;
  const last = p.split("/").pop() ?? "";
  if (last.includes(".")) return p;
  return p + "/";
}

export function mapPath(pathname) {
  let p = pathname || "/";
  if (!p.startsWith("/")) p = "/" + p;

  // 1. Explicit map (exact, then with/without trailing slash).
  if (EXPLICIT[p] !== undefined) return EXPLICIT[p];
  const alt = p.endsWith("/") ? p.slice(0, -1) : p + "/";
  if (EXPLICIT[alt] !== undefined) return EXPLICIT[alt];

  // 2. Gen 2: /blog/YYYY/MM/DD/{slug}/ -> /blog/{slug}/
  let m = p.replace(/^\\/blog\\/\\d{4}\\/\\d{2}\\/\\d{2}\\/(.+)$/, "/blog/$1");
  if (m !== p) return ensureTrailingSlash(m);

  // 3. Gen 1: /YYYY/MM/DD/{slug}/ -> /blog/{slug}/
  m = p.replace(/^\\/\\d{4}\\/\\d{2}\\/\\d{2}\\/(.+)$/, "/blog/$1");
  if (m !== p) return ensureTrailingSlash(m);

  // 4. Double-blog cleanup: /blog/blog/{slug}/ -> /blog/{slug}/
  m = p.replace(/^\\/blog\\/blog\\/(.+)$/, "/blog/$1");
  if (m !== p) return ensureTrailingSlash(m);

  // 5. Old category root: /category/{cat}/ -> /blog/category/{cat}/
  m = p.replace(/^\\/category\\/(.+)$/, "/blog/category/$1");
  if (m !== p) return ensureTrailingSlash(m);

  // 6. Live pass-through.
  return p;
}

export default {
  async fetch(request) {
    const url = new URL(request.url);
    return Response.redirect(DEST + mapPath(url.pathname) + url.search, 301);
  },
};
`;

fs.mkdirSync(OUT_DIR, { recursive: true });
fs.writeFileSync(path.join(OUT_DIR, "worker.js"), worker);
fs.writeFileSync(
  path.join(OUT_DIR, "explicit-map.json"),
  JSON.stringify(merged, null, 2) + "\n",
);

console.log(
  `[gen-redirect-worker] wrote workers/redirect/worker.js (${Object.keys(merged).length} explicit entries)`,
);
